import type { EmitResult, ModelPolicy, ProviderModel, Role } from "../types.js";

const CONFIG_PATH = ".codex/config.toml";

export function emitCodex(policy: ModelPolicy): EmitResult {
  const warnings: string[] = [];
  const lines: string[] = [];

  lines.push(`# generated by @razroo/iso-route — do not hand-edit`);
  lines.push(`model = ${tomlString(policy.default.model)}`);
  lines.push(`model_provider = ${tomlString(providerKey(policy.default.provider))}`);
  if (policy.default.reasoning) {
    lines.push(`model_reasoning_effort = ${tomlString(policy.default.reasoning)}`);
  }
  lines.push("");

  for (const role of policy.roles) {
    lines.push(`[profiles.${tomlKey(role.name)}]`);
    lines.push(`model = ${tomlString(role.model)}`);
    lines.push(`model_provider = ${tomlString(providerKey(role.provider))}`);
    if (role.reasoning) {
      lines.push(`model_reasoning_effort = ${tomlString(role.reasoning)}`);
    }
    lines.push("");
    if (role.fallback?.length) {
      warnings.push(
        `codex: role "${role.name}" fallback chain recorded in resolved map but not encoded in config.toml (Codex has no native fallback)`,
      );
    }
  }

  lines.push(...providerBlocks(policy, warnings));

  return {
    target: "codex",
    files: [file(CONFIG_PATH, `${lines.join("\n").trimEnd()}\n`)],
    warnings,
  };
}

function providerBlocks(policy: ModelPolicy, warnings: string[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const all: ProviderModel[] = [policy.default, ...policy.roles];
  for (const r of all) {
    const key = providerKey(r.provider);
    if (seen.has(key)) continue;
    seen.add(key);
    const block = providerBlock(r.provider);
    if (block) out.push(...block, "");
    else if (!codexReservedBuiltinProvider(r.provider))
      warnings.push(
        `codex: provider "${r.provider}" has no known TOML template — user must fill in [model_providers.${key}] manually`,
      );
  }
  return out;
}

/** Codex CLI reserves these IDs — `[model_providers.<id>]` overrides are rejected at load time. */
function codexReservedBuiltinProvider(p: ProviderModel["provider"]): boolean {
  return p === "openai" || p === "ollama";
}

function providerBlock(provider: ProviderModel["provider"]): string[] | null {
  switch (provider) {
    case "anthropic":
      return [
        `[model_providers.anthropic]`,
        `name = "Anthropic"`,
        `base_url = "https://api.anthropic.com/v1"`,
        `env_key = "ANTHROPIC_API_KEY"`,
      ];
    case "openai":
      // Built-in — use `model_provider = "openai"` only. Custom base URL:
      // top-level `openai_base_url` or `OPENAI_BASE_URL` (Codex docs).
      return null;
    case "google":
      return [
        `[model_providers.google]`,
        `name = "Google"`,
        `base_url = "https://generativelanguage.googleapis.com/v1beta"`,
        `env_key = "GOOGLE_API_KEY"`,
      ];
    case "openrouter":
      return [
        `[model_providers.openrouter]`,
        `name = "OpenRouter"`,
        `base_url = "https://openrouter.ai/api/v1"`,
        `env_key = "OPENROUTER_API_KEY"`,
      ];
    case "ollama":
      // Built-in — use `model_provider = "ollama"` (or `--oss`) only.
      return null;
    default:
      return null;
  }
}

function providerKey(p: ProviderModel["provider"]): string {
  return p;
}

function tomlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tomlKey(k: string): string {
  return /^[a-z0-9_-]+$/i.test(k) ? k : tomlString(k);
}

function file(path: string, contents: string) {
  return { path, bytes: Buffer.byteLength(contents, "utf8"), contents };
}

export type { Role };
